import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";

import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";

import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { Toaster } from "@/components/ui/sonner";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${jetBrainsMono.className}`}>
        <NuqsAdapter>
          <ConvexClientProvider>
            {children}
            <Toaster />
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
